name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black shellcheck-py

      - name: Python lint (ruff)
        run: ruff check .

      - name: Python format check (black)
        run: black --check .

      - name: Shellcheck
        run: shellcheck -V && find . -type f -name "*.sh" -print0 | xargs -0 -r shellcheck -S warning
